# set base image
FROM centos:centos6

# install packages
RUN yum install -y epel-release \
 && yum install -y bash-completion gcc git htop openssh-server rsync vim wget \
 && yum install -y https://get.docker.com/rpm/1.7.0/centos-6/RPMS/x86_64/docker-engine-1.7.0-1.el6.x86_64.rpm \
 && yum clean all \
 && /etc/init.d/sshd start \
 && /etc/init.d/sshd stop \
 && echo senhaboa | passwd --stdin root

# set command to run
ENTRYPOINT ["/usr/sbin/sshd", "-D"]
