# set base image
FROM centos:centos6

# install packages
RUN yum install -y epel-release \
 && yum install -y bash-completion gcc git htop openssh-server rsync vim wget \
 && yum clean all \
 && /etc/init.d/sshd start \
 && /etc/init.d/sshd stop \
 && echo senhaboa | passwd --stdin root

# set command to run
ENTRYPOINT ["/usr/sbin/sshd", "-D"]
